ktor:
  development: true
  deployment:
    port: 8082
    watch:
      - classes
      - resources
  application:
    modules:
      - ru.otus.music.search.ApplicationKt.module

jwt:
  #  secret: "secret"
  issuer: "http://0.0.0.0:8081/auth/realms/music-search"
  audience: "music-search-service"
  realm: "music-search"
  clientId: "music-search-service"
  certUrl: "http://0.0.0.0:8081/auth/realms/music-search/protocol/openid-connect/certs"
